ECHO OFF
TITLE Restart Node
COLOR 2
ECHO Starting Node...
START ./node/nodejs-portable
ECHO Instruction: Once node initializes, enter this command in the new window [node ./api.js usb]...
ECHO Please do not close the node command window while application is running...
PAUSE 