ECHO OFF
TITLE Start Application
COLOR 2
ECHO Starting Database...
START ./data/PostgreSQLPortable
ECHO Instruction: Please wait for separate command window to finish initializing...
ECHO Note: Please do not close the database command window while application is running...
PAUSE 
ECHO Starting Node...
START ./node/nodejs-portable
ECHO Instruction: Once node initializes, enter this command in the new window [node ./api.js usb]...
ECHO Note: Please do not close the node command window while application is running...
PAUSE 
ECHO Starting Server...
START ./server/usbwebserver
PAUSE 