ECHO OFF
TITLE Restart Database
COLOR 2
ECHO Starting Database...
START ../data/PostgreSQLPortable
ECHO Please wait for separate command window to finish initializing...
ECHO Please do not close the database command window while application is running...
PAUSE 
